---
title: " "
output: html_document
---

### **Recaudo Vigilancia - Cuota extra**


```{r setup, include=FALSE, }
library(dplyr)
library(knitr)
library(ggplot2)
library(scales) # para la función comma()
library(readxl)
library(formattable)
library(scales)
data <- read_excel("vecinos.xlsx", sheet = "cuota-extra")
```

```{r, echo=FALSE}
total <- c(sum(data$cuota, na.rm = TRUE))
```

```{r echo=FALSE}
# Crear formato de color con sombreado solo para valores mayores a cero y formato con comas sin decimales
formattable(data, 
            list(
              cuota = color_tile("white", "lightblue")
              #cuota = comma
            ))




```


```{r, echo=FALSE}
total = as.data.frame(total)
formattable(total,
             list(
              total = color_tile("white", "lightblue")
              #cuota = comma
            ))


```

<br><br> 
<br><br> 

<div class="box-blue">
<span style='color:#696969'> 
**Notas aclaratorias**

* Se recoge cuota extra para completar pagos de vigilancia del mes de diciembre de 2024 (faltante: $180.000.oo) e iniciar nuevo año con uan base ($260.000.oo) 

</div>


