---
title: " "
output: html_document
---

### **Recaudo Vigilancia - Enero 2025**


```{r setup, include=FALSE, }
library(dplyr)
library(knitr)
library(ggplot2)
library(readxl)
library(formattable)
data <- read_excel("vecinos.xlsx", sheet = "ene2025")

# Calculando los totales
recaudo_total <- data %>% 
  mutate(total = pago1 + pago2)

data$pago1 <- accounting(data$pago1)
data$pago2 <- accounting(data$pago2)
total_quincena1 <- accounting(sum(data$pago1, na.rm = TRUE))
total_quincena2 <-accounting(sum(data$pago2, na.rm = TRUE))
total_general <-  accounting(total_quincena1+total_quincena2)
```



```{r, echo=FALSE}
names(data) <- c("Placa", "Nombre", "1ra-quincena", "2da-quincena")

formattable(data,
             list(
              "1ra-quincena" = color_tile("white", "lightblue"),
              "2da-quincena" = color_tile("white", "lightblue")
            ))



```


<br/>

<div class="box-blue">

```{r, echo=FALSE}
kable(data.frame(
  TOTALES = c("Total 1ra Quincena", "Total 2da Quincena", "Recaudo Total"),
  Valor = c(total_quincena1, total_quincena2, total_general)
))
```

</div>